hackerspace-ntnu/Temple-Trashers

Assets/Animations/PandaAnimation.controller
Assets/Prefabs/PandaNew.prefab
Assets/Prefabs/PandaNew.prefab.meta

Added panda player AS A PREFAB

---

Assets/LeanTween/Examples.meta
Assets/PlayerManager.cs
Assets/PlayerStateController.cs
Assets/Scenes/Main.unity
Assets/Scripts/BaseController.cs
Assets/Scripts/CameraFocusController.cs

Players added.
All alpha goals are now met!

Implemented players in main scene.

---

Assets/Prefabs/Enemy/Enemy.prefab
Assets/Prefabs/Enemy/EnemyManager.prefab
Assets/Prefabs/Enemy/EnemyManager.prefab.meta
Assets/Prefabs/PlayerControls.inputactions
Assets/Scenes/Main.unity
Assets/Scripts/Enemy/Enemy.cs
Assets/Scripts/Enemy/EnemyManager.cs
Assets/Scripts/Enemy/Types.meta
Assets/Scripts/Enemy/Types/PlaceholderEnemy.cs
Assets/Scripts/Enemy/Types/PlaceholderEnemy.cs.meta
Assets/Scripts/GameState.meta
Assets/Scripts/GameState/EnemyWave.cs
Assets/Scripts/GameState/EnemyWave.cs.meta
Assets/Scripts/GameState/EnemyWaveManager.cs
Assets/Scripts/GameState/EnemyWaveManager.cs.meta
Assets/Scripts/GameState/Levels.meta
Assets/Scripts/GameState/Levels/level1_waves.txt
Assets/Scripts/GameState/Levels/level1_waves.txt.meta
Assets/Scripts/Player/PlayerControls.cs
Assets/Scripts/Player/PlayerStateController.cs
Assets/Scripts/Util/WaveFileParser.cs
Assets/Scripts/Util/WaveFileParser.cs.meta

*This PR depends on #25 and should change base to `develop` after it has been merged.*
This introduces a manager that handles the state of the enemy waves, as well as spawning the enemies. The contents of each level's waves are controlled through a text file (see [this example file](https://github.com/SondreHus/HackerSpace_NTNU_SpillProsjekt/blob/04f876a978edef5824b10a0a904ec84d76c9424b/Assets/Scripts/GameState/Levels/level1_waves.txt)). In it, one can set the number of types of enemies to spawn each wave, and add pauses between enemy spawns. After a wave is completed, the next wave starts after the signal has been given (i.e. calling [`ReadyForNextWave()`](https://github.com/SondreHus/HackerSpace_NTNU_SpillProsjekt/blob/e3b22161fe43069e7cdbaa909b1f23ae280cebc4/Assets/Scripts/GameState/Ene …

Enemy wave manager

---

Assets/Prefabs/UI/InventoryManager.prefab
Assets/Prefabs/UI/InventoryManager.prefab.meta
Assets/Prefabs/UI/ResourceUI.prefab
Assets/Prefabs/UI/ResourceUI.prefab.meta
Assets/Scenes/Main.unity
Assets/SciptableObjects/TowerScript.cs
Assets/Scripts/Interactables/Loot.cs
Assets/Scripts/Player/PlayerStateController.cs
Assets/Scripts/Player/PlayerUi.cs
Assets/Scripts/UI/ResourceUI.cs
Assets/Scripts/UI/ResourceUI.cs.meta
Assets/Scripts/UI/UIController.cs
Assets/Scripts/Util/InventoryManager.cs
Assets/Scripts/Util/InventoryManager.cs.meta

A whole system including UI, inventory, and buying/gaining resource functionality.
The functionality of these handles resources (from loot), the way thay are displayed to players, and how they are used by players (buying turrets).

Inventory manager

---

Assets/Scripts/Player/PlayerUi.cs
Assets/Scripts/UI/UIControllerWheel.cs

Fixed a bug.

---

Assets/Animations/Towers/LightningTurret.meta
Assets/Animations/Towers/LightningTurret/Ligningturret.controller
Assets/Animations/Towers/LightningTurret/Ligningturret.controller.meta
Assets/Animations/Towers/LightningTurret/ShootLightning.anim
Assets/Animations/Towers/LightningTurret/ShootLightning.anim.meta
Assets/Prefabs/Towers/LightningTurret/LightningTurret.prefab

Updated the lightningturret prefab

---

Assets/Materials/Terrain/Mat 1.mat
Assets/Materials/Terrain/Mat 2.mat
Assets/Materials/Terrain/Mat 3.mat
Assets/Materials/Terrain/Mat 4.mat
Assets/Prefabs/Terrain/HexCell.prefab
Assets/Scenes/Main.unity
Assets/Scripts/Terrain/HexCell.cs
Assets/VFX/DrainRay.prefab

Terrain makeover!

---

Assets/Scripts/Enemy/Enemy.cs
Assets/Scripts/GameState/BaseController.cs

The base had a problem where it would never go to a game over state. After some inspection, I found this to be true for enemies too. This i s now fixed.

Updated the ondeath delegate so base + enemy dies properly.

---

Assets/Scenes/Main.unity
README.md

Readme updated

---

README.md

Updated readme with article link

---

Assets/Scripts/Player/PlayerStateController.cs
Assets/Scripts/Player/PlayerUi.cs

Fixed two bugs discovered in the demo.

Bugfixes to playerstate

---

Assets/Models/fauna.fbx
Assets/Models/fauna.fbx.meta
Assets/Prefabs/Terrain/Decor/Tree Border.prefab
Assets/Prefabs/Terrain/Decor/Tree_1.prefab
Assets/Prefabs/Terrain/Decor/color palette.png
Assets/Prefabs/Terrain/Decor/color palette.png.meta
Assets/Prefabs/Terrain/Decor/fauna material.mat
Assets/Prefabs/Terrain/Decor/fauna material.mat.meta

*Description copied from #54:*
added some new models for fauna:
Flower, Tree, Fern, Rocks
Updated the old tree model

Add fauna models

---

Assets/Models/Terrain/Scenery/ruins.fbx
Assets/Models/Terrain/Scenery/ruins.fbx.meta
Assets/Prefabs/Terrain/Scenery/Ruins.prefab
Assets/Prefabs/Terrain/Scenery/Ruins.prefab.meta

Added ruins prefab which can be placed on tall terrain
please merge

Ruins prefab

---

Assets/Audio/SFX.meta
Assets/Audio/SFX/Base.meta
Assets/Audio/SFX/Base/crystal_absorption.wav
Assets/Audio/SFX/Base/crystal_absorption.wav.meta
Assets/Audio/SFX/Hitsounds.meta
Assets/Audio/SFX/Hitsounds/box_punch.wav
Assets/Audio/SFX/Hitsounds/box_punch.wav.meta
Assets/Audio/SFX/Hitsounds/whip_crack.mp3
Assets/Audio/SFX/Hitsounds/whip_crack.mp3.meta
Assets/Audio/SFX/Tower.meta
Assets/Audio/SFX/Tower/hammer_hit.wav
Assets/Audio/SFX/Tower/hammer_hit.wav.meta
Assets/Audio/SFX/Tower/pan_hit.wav
Assets/Audio/SFX/Tower/pan_hit.wav.meta
Assets/Audio/SFX/Tower/whoosh.mp3
Assets/Audio/SFX/Tower/whoosh.mp3.meta
Assets/Audio/SFX/Tower/zap.mp3
Assets/Audio/SFX/Tower/zap.mp3.meta
Assets/Prefabs/Audio/AudioManager.prefab
Assets/Prefabs/Base/Base.prefab
Assets/Prefabs/Enemy/Enemies/Skeleton.prefab
Assets/Prefabs/Towers/AxeTurret/AxeTurret.prefab
Assets/Prefabs/Towers/LightningTurret/LightningTurret.prefab
Assets/Scripts/Enemy/Enemies/Skeleton/SkeletonController.cs
Assets/Scripts/GameState/BaseController.cs
Assets/Scripts/Towers/Repair logic/RepairController.cs
Assets/Scripts/Towers/Specific towers/Axe turret/AxeTowerAnimationController.cs
Assets/Scripts/Towers/Specific towers/Lightning turret/LightningShootable.cs

All soundFX are implemented with load type "streaming".

Added soundFXs to the game!

---

Assets/Scripts/Player/PlayerUi.cs

@TArchetype  and I discussed this change and concluded that the new behaviour is much more intuitive to control.

Updated UIwheel to be active after stick input

---

Assets/Materials/Towers/AxeTurret/AxeTurretMain.mat
Assets/Prefabs/Towers/LavaTurret/LavaTurret.prefab
Assets/Prefabs/UI/HUD.prefab
Assets/Prefabs/UI/basicRadialUi.prefab
Assets/Scenes/Endless_Mode.unity

Fixed an issue where vfx and transparent object were visible through healthbar. 
Fixed the camera angle to be 50 degrees. 
Added dotted line to llava turret.

Several small fixes to vfx and scene

---

README.md

Currently only missing confirmation from magsve, but can be merged regardless when build is ready

Updated credit names from aliases to actual names.

---

Assets/InputSettings/PlayerControls.inputactions
Assets/Models/PlayerCharacters/Strongman/Strongman.fbx.meta
Assets/Prefabs/Towers/LavaTurret/LavaExplosion.prefab
Assets/Scenes/Main_Menu.unity
Assets/Scenes/Options.unity
Assets/Scripts/GameState/BaseController.cs
Assets/Scripts/GameState/GameOverScreen.cs
Assets/Scripts/GameState/PauseManager.cs
Assets/Scripts/Player/PlayerControls.cs

- Made players able to add input on gamepad stick input and not just button press, as per valve's request.
- Lowered the volume of lava explosion prefab

Steam requirements + minor polish

---

Assets/Scenes/Gallery.unity
Assets/Scripts/GameState/BaseController.cs
Assets/Scripts/GameState/GameOverScreen.cs
Assets/Scripts/GameState/PauseManager.cs

- Fixed slow-mo bug where game would be permanently slowed under certain conditions
- Endless mode given more trees to balance out ortographic view
- Updated sprites in gallery after previous PR changed sprite in main menu and not in gallery
- Hide mouse cursor when not relevant (normal gameplay)

Fixed permanent slow-mo bug 

---

Assets/Materials/Base/BaseMat2.mat
Assets/Prefabs/Player/Characters/Player_Dahl.prefab
Assets/Scripts/GameState/BaseController.cs
Assets/Scripts/Player/PlayerRagdollController.cs
Assets/Scripts/Player/PlayerSpecificManager.cs
Assets/Scripts/Player/PlayerStateController.cs
Assets/Textures/Menu/lifebar.png.meta

This is a quick respawn animation which allows players to better understand where their player characters are when they die.
In addition adjusted the base healthbar texture so that we removed the one pixel glitch that was showing at certain resolutions

Created a respawn animation for the players.

---

Assets/Prefabs/Crystal Loot/Loot Crystal.prefab

Increases size of crystal loot UI
Fixes issue #166

Fix/crystal UI
